### PR TITLE
External File System for ESP8266

### PR DESCRIPTION
**Pull request by wallaroo**
HI this is only an help request because these break OTA updates.

like you can see i created a FS image of 2M-16k size to write at 0x200000. (like discussed in  #151 )

i also created a javascript method Sys.fs.jump() to move between "normal" and "external" FS.

all works well: i'm able to write and read both file systems but...

OTA doesn't work anymore :( 
(after update the board enters in a loop of reboots)

i'm sure you have the answer ;-)

---

This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose-iot/152)

### CODE REVIEW

**Comment by cpq** [comment]
Hi Michele ,
could you elaborate on why you'd like to have two filesystems, please?

**Comment by mmikulicic** [comment]
@cpq: I believe this is related to #151

**Comment by wallaroo** [comment]
Hi Sergey,
 my reasons are:
- for my project not all nodes will have a continuos internet connection but must have a pretty complex wui so i can't use a cdn to serve library like jquery that with his 85K already overflows the current available space in FS (~60K).

- i have to log some data (~5KB per day) and "harvest" them with regularity with a client (smart phone).

i know, i can attach an SD reader via SPI but this would increase cost significantly and don't need more than 1,5 MB

why i choose mongoose-iot? primarily because is the easiest way to implement the simple dynamic rule engine that i need (rule=function(){...}); secondarily because i like it, i have other ideas to use it and i trust in his growth...

**Comment by cpq** [comment]
Thanks Michele.
Yeah, the OTA does not work in that case because it wants that part of flash that you're using for the FS.

**Comment by cpq** [comment]
Apologies we haven't looked at this closely.
And mongoose os gone a long way ahead.
@wallaroo is it still relevant to you?

**Comment by cpq** [comment]
Closing as rotten

**Pull request closed without merging**
