### PR TITLE
Add ESP32-S3 to ESP32 docker build

### PR DESCRIPTION
**Pull request by duncandrennan**
* Added a docker image for building for ESP32-S3
* Current builds against v4.4.1 of the ESP-IDF which it fetches from https://github.com/duncandrennan/esp-idf.git using DOCKER_TAG=4.4-dev
* Has been tested to work building the bootloader (and can read/write flash with the bootloader stub)
* Work towards issue #597

### CODE REVIEW

**Comment by duncandrennan** [comment]
* Updated this to use Mongoose OS ESP-IDF
* Builds with DOCKER_TAG=4.4.1-r1

**Comment by rojer** [comment]
i think we can support all ESP32 devices (or all devices supported by ESP-IDF, really) with one image, we just need to include the toolchains

**Comment by duncandrennan** [comment]
That makes sense. The only thing that I'm not sure about is how the environment variable MGOS_TARGET_GDB propagates through the mos system, as well as how rom.bin/elf are used. I see debug_core_dump.go (in mos tool) configures the platformDebugParams, so the rom files can be set that way. Looking further it looks like the MGOS_TARGET_GDB could also be shifted to the platformDebugParms and then appended in the same way as dp.extraServeCoreArgs.

Then each platform could have its own define, e.g. MGOS_TARGET_GDB_ESP32 (or ESP32S3, etc.).

**Comment by duncandrennan** [comment]
I've updated this to build single ESP32 (ESP-IDF) docker image. I've left the existing defines/files (in particular rom.bin/elf and MGOS_TARGET_GDB) and added items for the -S3/C3. -S3 ROM is not yet available from the download link provided here, https://docs.espressif.com/projects/esp-idf/en/v4.4.1/esp32s3/api-guides/core_dump.html#rom-functions-in-backtraces.

Also updated the PR  mongoose-os/mos#72

**Comment by rojer** [comment]
please rebase

**Comment by duncandrennan** [comment]
Rebased

**Comment by rojer** [comment]
merged, thanks!

**Pull request merged**
