### PR TITLE
Fix C++ build

### PR DESCRIPTION
**Pull request by neoautomata**
Fixes [Issue 241](https://github.com/cesanta/mongoose-os/issues/241) and [Issue 245](https://github.com/cesanta/mongoose-os/issues/245).

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose-os/263)

### CODE REVIEW

**Comment by neoautomata** [comment]
Is anyone looking at this? I signed the CLA before sending the pull request.

**Comment by cpq** [comment]
Ruslan, please verify and integrate.

**Comment by ruslanvaliullin** [comment]
ok

**Comment by cpq** [comment]
That's done, closing

**Pull request closed without merging**
